ALTER TABLE `SaleItem` DROP FOREIGN KEY `SaleItem_productId_fkey`;
ALTER TABLE `PurchaseItem` DROP FOREIGN KEY `PurchaseItem_productId_fkey`;

ALTER TABLE `SaleItem`
  ADD COLUMN `productBarcode` VARCHAR(191) NULL,
  ADD COLUMN `productSku` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `productName` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `productMetal` ENUM('GOLD', 'SILVER', 'PLATINUM', 'DIAMOND', 'OTHER') NULL,
  ADD COLUMN `productPurity` VARCHAR(191) NULL,
  ADD COLUMN `grossWeight` DECIMAL(12, 3) NOT NULL DEFAULT 0,
  MODIFY COLUMN `productId` INTEGER NULL;

ALTER TABLE `PurchaseItem`
  ADD COLUMN `productSku` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `productName` VARCHAR(191) NOT NULL DEFAULT '',
  MODIFY COLUMN `productId` INTEGER NULL;

ALTER TABLE `SaleItem`
  ADD CONSTRAINT `SaleItem_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `PurchaseItem`
  ADD CONSTRAINT `PurchaseItem_productId_fkey` FOREIGN KEY (`productId`) REFERENCES `Product`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
