
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phone: 'phone',
  email: 'email',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierScalarFieldEnum = {
  id: 'id',
  name: 'name',
  phone: 'phone',
  email: 'email',
  address: 'address',
  gstin: 'gstin',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  barcode: 'barcode',
  sku: 'sku',
  name: 'name',
  category: 'category',
  metal: 'metal',
  purity: 'purity',
  grossWeight: 'grossWeight',
  stoneWeight: 'stoneWeight',
  netWeight: 'netWeight',
  quantity: 'quantity',
  reorderLevel: 'reorderLevel',
  purchasePrice: 'purchasePrice',
  sellingPrice: 'sellingPrice',
  makingChargePerGram: 'makingChargePerGram',
  makingChargeType: 'makingChargeType',
  makingChargeValue: 'makingChargeValue',
  location: 'location',
  notes: 'notes',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  quantity: 'quantity',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.PurchaseScalarFieldEnum = {
  id: 'id',
  purchaseNumber: 'purchaseNumber',
  supplierId: 'supplierId',
  purchaseDate: 'purchaseDate',
  subtotal: 'subtotal',
  discount: 'discount',
  total: 'total',
  paid: 'paid',
  paymentMethod: 'paymentMethod',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseItemScalarFieldEnum = {
  id: 'id',
  purchaseId: 'purchaseId',
  productId: 'productId',
  quantity: 'quantity',
  unitCost: 'unitCost',
  lineTotal: 'lineTotal'
};

exports.Prisma.SaleScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  customerId: 'customerId',
  saleDate: 'saleDate',
  subtotal: 'subtotal',
  discount: 'discount',
  gstRate: 'gstRate',
  gstAmount: 'gstAmount',
  total: 'total',
  urdOffset: 'urdOffset',
  paid: 'paid',
  cashPaid: 'cashPaid',
  upiPaid: 'upiPaid',
  balance: 'balance',
  paymentMethod: 'paymentMethod',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SaleItemScalarFieldEnum = {
  id: 'id',
  saleId: 'saleId',
  productId: 'productId',
  quantity: 'quantity',
  weight: 'weight',
  unitPrice: 'unitPrice',
  metalRate: 'metalRate',
  metalAmount: 'metalAmount',
  makingCharge: 'makingCharge',
  makingChargeType: 'makingChargeType',
  makingChargeValue: 'makingChargeValue',
  taxableAmount: 'taxableAmount',
  lineTotal: 'lineTotal'
};

exports.Prisma.DailyRateScalarFieldEnum = {
  id: 'id',
  rateDate: 'rateDate',
  gold22k: 'gold22k',
  gold24k: 'gold24k',
  silver: 'silver',
  note: 'note',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BarcodeSequenceScalarFieldEnum = {
  prefix: 'prefix',
  lastNumber: 'lastNumber',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerLedgerScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  saleId: 'saleId',
  type: 'type',
  amount: 'amount',
  paymentMethod: 'paymentMethod',
  reference: 'reference',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.RepairScalarFieldEnum = {
  id: 'id',
  repairNumber: 'repairNumber',
  customerId: 'customerId',
  itemDescription: 'itemDescription',
  metal: 'metal',
  grossWeight: 'grossWeight',
  issueDescription: 'issueDescription',
  estimatedCharge: 'estimatedCharge',
  finalCharge: 'finalCharge',
  advancePaid: 'advancePaid',
  advancePaymentMethod: 'advancePaymentMethod',
  dueDate: 'dueDate',
  status: 'status',
  receivedAt: 'receivedAt',
  deliveredAt: 'deliveredAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CashbookEntryScalarFieldEnum = {
  id: 'id',
  entryDate: 'entryDate',
  type: 'type',
  paymentMethod: 'paymentMethod',
  description: 'description',
  amount: 'amount',
  reference: 'reference',
  notes: 'notes',
  customerId: 'customerId',
  syncLedger: 'syncLedger',
  createdAt: 'createdAt'
};

exports.Prisma.UrdPurchaseScalarFieldEnum = {
  id: 'id',
  purchaseNumber: 'purchaseNumber',
  customerId: 'customerId',
  purchaseDate: 'purchaseDate',
  metal: 'metal',
  purity: 'purity',
  grossWeight: 'grossWeight',
  netWeight: 'netWeight',
  ratePerGram: 'ratePerGram',
  totalAmount: 'totalAmount',
  saleOffset: 'saleOffset',
  paid: 'paid',
  paymentMethod: 'paymentMethod',
  description: 'description',
  notes: 'notes',
  saleId: 'saleId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.CustomerOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  email: 'email',
  address: 'address'
};

exports.Prisma.SupplierOrderByRelevanceFieldEnum = {
  name: 'name',
  phone: 'phone',
  email: 'email',
  address: 'address',
  gstin: 'gstin'
};

exports.Prisma.ProductOrderByRelevanceFieldEnum = {
  barcode: 'barcode',
  sku: 'sku',
  name: 'name',
  category: 'category',
  purity: 'purity',
  location: 'location',
  notes: 'notes'
};

exports.Prisma.StockMovementOrderByRelevanceFieldEnum = {
  note: 'note'
};

exports.Prisma.PurchaseOrderByRelevanceFieldEnum = {
  purchaseNumber: 'purchaseNumber',
  notes: 'notes'
};

exports.Prisma.SaleOrderByRelevanceFieldEnum = {
  invoiceNumber: 'invoiceNumber',
  notes: 'notes'
};

exports.Prisma.DailyRateOrderByRelevanceFieldEnum = {
  rateDate: 'rateDate',
  note: 'note'
};

exports.Prisma.BarcodeSequenceOrderByRelevanceFieldEnum = {
  prefix: 'prefix'
};

exports.Prisma.CustomerLedgerOrderByRelevanceFieldEnum = {
  reference: 'reference',
  note: 'note'
};

exports.Prisma.RepairOrderByRelevanceFieldEnum = {
  repairNumber: 'repairNumber',
  itemDescription: 'itemDescription',
  issueDescription: 'issueDescription',
  notes: 'notes'
};

exports.Prisma.CashbookEntryOrderByRelevanceFieldEnum = {
  entryDate: 'entryDate',
  description: 'description',
  reference: 'reference',
  notes: 'notes'
};

exports.Prisma.UrdPurchaseOrderByRelevanceFieldEnum = {
  purchaseNumber: 'purchaseNumber',
  purity: 'purity',
  description: 'description',
  notes: 'notes'
};
exports.MetalType = exports.$Enums.MetalType = {
  GOLD: 'GOLD',
  SILVER: 'SILVER',
  PLATINUM: 'PLATINUM',
  DIAMOND: 'DIAMOND',
  OTHER: 'OTHER'
};

exports.MakingChargeType = exports.$Enums.MakingChargeType = {
  FIXED: 'FIXED',
  PER_GRAM: 'PER_GRAM',
  PERCENTAGE: 'PERCENTAGE'
};

exports.ProductStatus = exports.$Enums.ProductStatus = {
  AVAILABLE: 'AVAILABLE',
  SOLD_OUT: 'SOLD_OUT',
  IN_REPAIR: 'IN_REPAIR',
  INACTIVE: 'INACTIVE'
};

exports.MovementType = exports.$Enums.MovementType = {
  OPENING: 'OPENING',
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  REPAIR_OUT: 'REPAIR_OUT',
  REPAIR_IN: 'REPAIR_IN'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CREDIT: 'CREDIT',
  MIXED: 'MIXED'
};

exports.LedgerEntryType = exports.$Enums.LedgerEntryType = {
  SALE_CREDIT: 'SALE_CREDIT',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.RepairStatus = exports.$Enums.RepairStatus = {
  RECEIVED: 'RECEIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  READY: 'READY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

exports.CashbookType = exports.$Enums.CashbookType = {
  IN: 'IN',
  OUT: 'OUT'
};

exports.Prisma.ModelName = {
  Customer: 'Customer',
  Supplier: 'Supplier',
  Product: 'Product',
  StockMovement: 'StockMovement',
  Purchase: 'Purchase',
  PurchaseItem: 'PurchaseItem',
  Sale: 'Sale',
  SaleItem: 'SaleItem',
  DailyRate: 'DailyRate',
  BarcodeSequence: 'BarcodeSequence',
  CustomerLedger: 'CustomerLedger',
  Repair: 'Repair',
  CashbookEntry: 'CashbookEntry',
  UrdPurchase: 'UrdPurchase'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
